# Review Session 3 - Tools of Economic Complexity

Linear algebra and complexity variables

**Outline**

- Linear algebra basics
- Networks - construction and metrics
	- Adjacency matrix
	- Edge lists
	- Degree distributions
	- Centrality metrics
	- “Network backbiting” - Michele / Frank
- Complexity metrics
	- ECI / PCI / Density
	- Industry spaces - co-production / co-location / co-coordination
- Density regressions
	- Growth vs density, country FE
	- Product appearances vs density, country FE

In [1]:
%reset -f

In [2]:
import os
import re
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
PROJ = Path(os.path.realpath("."))
ROOT = PROJ.parents[1]
DATA = ROOT / "data/"

In [4]:
# sys.path.append(str(PROJ))
# sys.path.append(str(ROOT / "src"))
# from gee_utils import *

# Linear Algebra Basics

## Arrays, matrices, and indexing

In [10]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v = np.array([[1], [2], [3]])

In [11]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
v

array([[1],
       [2],
       [3]])

In [13]:
M.shape

(3, 3)

In [14]:
v.shape

(3, 1)

In [15]:
np.array([1, 2, 3]).shape

(3,)

In [16]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Indexing: selecting elements of list / arrays / matrices based on their positions

In [21]:
test_list = ["a", "b", "c", "d", "e"]
test_list[3:5]

['d', 'e']

In [26]:
test_arr = np.array(range(100, 120))
test_arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119])

In [27]:
test_arr[5:8]

array([105, 106, 107])

In [29]:
test_mat = np.random.randint(30, 60, (5, 5))
test_mat

array([[51, 30, 59, 34, 59],
       [34, 57, 34, 35, 46],
       [40, 34, 39, 58, 33],
       [41, 37, 46, 46, 49],
       [39, 49, 48, 57, 58]])

In [32]:
test_mat[:3, 1:3]

array([[30, 59],
       [57, 34],
       [34, 39]])

## Dot and cross products

In [35]:
A = np.random.randint(0, 5, (6, 7))
B = np.random.randint(0, 6, (7, 2))

In [36]:
A @ B

array([[39, 30],
       [39, 46],
       [36, 47],
       [31, 36],
       [28, 21],
       [23, 49]])

In [5]:
# Load proximities
# you could load your own saved proximity data
proximity_url = (
    "http://intl-atlas-downloads.s3.amazonaws.com/atlas_2_16_6/hs92_proximities.csv"
)
proximity_df = pd.read_csv(
    proximity_url,
    dtype={"commoditycode_1": str, "commoditycode_2": str, "proximity": float},
)
proximity_df.head()

commoditycode_1 commoditycode_2  proximity
0            0101            0101   0.000000
1            0101            0102   0.277778
2            0101            0103   0.352941
3            0101            0104   0.260870
4            0101            0105   0.296296